version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pravax}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pravax}
      POSTGRES_DB: ${POSTGRES_DB:-pravax}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pravax_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pravax}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - pravax_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pravax_pg_data:
  pravax_redis_data:


